```{r}
#import packages
require('jsonlite')
library(dplyr)
```

```{r}
# Convert the data source format (JSON) to the dataframe.
Result <- fromJSON(file.choose())

```

```{r}
#Tidy up the date format to become readable, i.e., 2nd Sep 2021 => 2/9/2021.
#Result$date <- as.Date(Result$date, "%d%B%Y"); Result$date
delete_word = c("st","rd","nd","th")
Result$date <- gsub(paste0(delete_word,collapse = "|"),"", Result$date)
Result$date <- gsub(paste0(" ",collapse = "|"),"/", Result$date)

Result$date <-gsub(paste0("Sep",collapse = "|"),"9", Result$date)
Result$date <-gsub(paste0("Aug",collapse = "|"),"8", Result$date)
unique(Result$date)
```

```{r}
#Fill all missing data with 0s except the sq. column.
df <- data.frame()
df <- Result$sq.
Result[is.na(Result)] <- 0
Result$sq. <- df

cbind(
   lapply(
     lapply(Result, is.na)
     , sum)
   )
```

```{r}
#Aggregate the number of corresponding facilities (Bed, Baths, Reception)
Result$bed = as.numeric(Result$bed) 
Result$beds = as.numeric(Result$beds)
Result$bath = as.numeric(Result$bath)
Result$baths = as.numeric(Result$baths)
Result$reception = as.numeric(Result$reception)
Result$receptions = as.numeric(Result$receptions)

Result$beds = Result$bed + Result$beds
Result$baths = Result$bath + Result$baths
Result$receptions = Result$reception + Result$receptions
Result = subset(Result, select = -c(bed, bath, reception))

Result <- Result[,c(1,2,3,4,5,6,9,7,8,10)]
```
